### ISSUE TITLE
Not working on Android 14

### ISSUE THREAD

**Issue by alder711** [pp3345/ykDroid#29]
Hello. This is a wonderful app, thank you for all of your hard work.

## Environment
I am currently trying this project in conjunction with [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android) with a Keepass database that requires both a master key and Yubikey challenge-response using the [KeeChallenge plugin](https://keepass.info/plugins.html#keechl).

I have successfully tested this combination in Android 12 using current app versions.

## The Issue
When I try this combination in GrapheneOS with Android 14, I am able to get to the prompt to attach/swipe the YubiKey as usual, but when I attach/swipe my YubiKey, the slot selector at the bottom of the prompt just disappears and then reappears.

Android 14 is still relatively recent in its debut, so please let me know if you need more information.

**Comment by alder711** [comment]
When using my Yubikey via NFC, I see this in the output of `adb logcat`:
```
12-08 18:25:26.435 25517 25517 E ykDroid : Error during challenge-response request
12-08 18:25:26.435 25517 25517 E ykDroid : java.lang.ArrayIndexOutOfBoundsException: src.length=2 srcPos=0 dst.length=20 dstPos=0 length=20
12-08 18:25:26.435 25517 25517 E ykDroid : 	at java.lang.System.arraycopy(System.java:527)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at net.pp3345.ykdroid.apdu.response.ykoath.PutResponseApdu.getResult(PutResponseApdu.java:14)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at net.pp3345.ykdroid.yubikey.NfcYubiKey.challengeResponse(NfcYubiKey.java:66)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at net.pp3345.ykdroid.ChallengeResponseActivity$1.doInBackground(ChallengeResponseActivity.java:102)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at net.pp3345.ykdroid.ChallengeResponseActivity$1.doInBackground(ChallengeResponseActivity.java:96)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-08 18:25:26.435 25517 25517 E ykDroid : 	at java.lang.Thread.run(Thread.java:1012)
12-08 18:25:26.436 25517 25517 I ActivityThread: Schedule relaunch activity: net.pp3345.ykdroid.ChallengeResponseActivity
12-08 18:25:26.446   765 19852 W gralloc4: Unable to set buffer name VRI[ChallengeResponseActivity]#1(BLAST Consumer)1: File name too long
```

**Comment by alder711** [comment]
When using the Yubikey via USB, I see this error:
```
12-08 19:00:01.707 I/ImeTracker(1663): net.pp3345.ykdroid:a8fc96a8: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_SAME_WINDOW_FOCUSED_WITHOUT_EDITOR
12-08 19:00:01.707 I/ImeTracker(1663): net.pp3345.ykdroid:a8fc96a8: onCancelled at PHASE_SERVER_SHOULD_HIDE
12-08 19:00:06.034 E/ykDroid (15686): Error during challenge-response request
12-08 19:00:06.034 E/ykDroid (15686): net.pp3345.ykdroid.yubikey.TimeoutException
12-08 19:00:06.034 E/ykDroid (15686):   at net.pp3345.ykdroid.yubikey.UsbYubiKey.waitForStatus(UsbYubiKey.java:278)
12-08 19:00:06.034 E/ykDroid (15686):   at net.pp3345.ykdroid.yubikey.UsbYubiKey.readResponse(UsbYubiKey.java:285)
12-08 19:00:06.034 E/ykDroid (15686):   at net.pp3345.ykdroid.yubikey.UsbYubiKey.challengeResponse(UsbYubiKey.java:184)
12-08 19:00:06.034 E/ykDroid (15686):   at net.pp3345.ykdroid.ChallengeResponseActivity$1.doInBackground(ChallengeResponseActivity.java:102)
12-08 19:00:06.034 E/ykDroid (15686):   at net.pp3345.ykdroid.ChallengeResponseActivity$1.doInBackground(ChallengeResponseActivity.java:96)
12-08 19:00:06.034 E/ykDroid (15686):   at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-08 19:00:06.034 E/ykDroid (15686):   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-08 19:00:06.034 E/ykDroid (15686):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-08 19:00:06.034 E/ykDroid (15686):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-08 19:00:06.034 E/ykDroid (15686):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-08 19:00:06.034 E/ykDroid (15686):   at java.lang.Thread.run(Thread.java:1012)
12-08 19:00:07.044 I/ActivityThread(15686): Schedule relaunch activity: net.pp3345.ykdroid.ChallengeResponseActivity
```

**Comment by alder711** [comment]
Turns out this was a PEBCAK error. I forgot that challenge-response was set up on slot 2.
